CREATE TABLE users (
   id int(11) NOT NULL AUTO_INCREMENT,
   user_fname varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
   user_lname varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
   user_rg varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
   user_orgao varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
   user_cpf varchar(11) COLLATE utf8mb4_unicode_ci NOT NULL,
   user_telefone varchar(15) COLLATE utf8mb4_unicode_ci NOT NULL,
   user_datan varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
   user_nacionalidade varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
   user_npai varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
   user_nmae varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
   user_ecivil varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
   user_regime varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
   user_email varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
   user_cep varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
   user_logradouro varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
   user_numero varchar(5) COLLATE utf8mb4_unicode_ci NOT NULL,
   user_complemento varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
   user_bairro varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
   user_cidade varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
   user_estado varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
   user_pais varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
   PRIMARY KEY (id)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;